/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package sweetBank;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author davidmunro && Hassan
 */
public class TransactionTransfer extends javax.swing.JFrame {

    private static String email, personNumber;
    private final DBcon con = new DBcon();
    private int passwordAttempts = 0;

    /**
     * Creates new form TransactionTransfer
     */
    public TransactionTransfer(String a, String i) {
        email = a;
        personNumber = i;
        initComponents();
        confirmButton.setVisible(false);
        personalLabel.setVisible(false);
        textPersonal.setVisible(false);
        labelCompany.setVisible(false);
        textCompany.setVisible(false);
        companyNameLabel.setVisible(false);
        companyNameText.setVisible(false);
        transferToAccLabel.setVisible(false);
        transferToText.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        transferToAccLabel = new javax.swing.JLabel();
        transferToText = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        transferAmountText = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        transferNote = new javax.swing.JTextField();
        okButton = new javax.swing.JButton();
        confirmButton = new javax.swing.JButton();
        passwordField = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        cancelButton = new javax.swing.JButton();
        personalLabel = new javax.swing.JLabel();
        textPersonal = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        transferChoiceCombo = new javax.swing.JComboBox();
        labelCompany = new javax.swing.JLabel();
        textCompany = new javax.swing.JTextField();
        companyNameLabel = new javax.swing.JLabel();
        companyNameText = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        jLabel1.setText("Transfer");

        transferToAccLabel.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        transferToAccLabel.setText("Transfer to (Account no)");

        transferToText.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        jLabel3.setText("Amount");

        transferAmountText.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        jLabel4.setText("KR");

        jLabel5.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        jLabel5.setText("Note");

        transferNote.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N

        okButton.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        confirmButton.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        confirmButton.setText("Confirm");
        confirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmButtonActionPerformed(evt);
            }
        });

        passwordField.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        passwordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordFieldActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        jLabel6.setText("Please enter password to confirm :");

        cancelButton.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        personalLabel.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        personalLabel.setText("Transfer to (Personal no)");

        textPersonal.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N

        jLabel8.setText("Type of transfer");

        transferChoiceCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Choose", "Person", "Company" }));
        transferChoiceCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transferChoiceComboActionPerformed(evt);
            }
        });

        labelCompany.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        labelCompany.setText("Transfer to (Company no)");

        companyNameLabel.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        companyNameLabel.setText("Transfer to (Company name)");

        companyNameText.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        companyNameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                companyNameTextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(confirmButton)
                        .addGap(67, 67, 67)
                        .addComponent(cancelButton))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8)
                        .addGap(43, 43, 43)
                        .addComponent(transferChoiceCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(transferToAccLabel)
                                .addGap(59, 59, 59)
                                .addComponent(transferToText, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(okButton))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(179, 179, 179)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(transferNote, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(transferAmountText, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel4))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(personalLabel)
                                    .addComponent(labelCompany)
                                    .addComponent(companyNameLabel))
                                .addGap(52, 52, 52)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(textCompany, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(textPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(companyNameText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(transferChoiceCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(transferToAccLabel)
                    .addComponent(transferToText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCompany)
                    .addComponent(textCompany, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(personalLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(companyNameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(transferAmountText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(transferNote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(okButton))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(confirmButton)
                            .addComponent(cancelButton))
                        .addGap(26, 26, 26))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(companyNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void passwordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordFieldActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void confirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmButtonActionPerformed
        if (transferChoiceCombo.getSelectedIndex() == 1) {
            int accNo = Integer.parseInt(transferToText.getText());
            int persNo = Integer.parseInt(textPersonal.getText());
            String note = transferNote.getText();
            float transAm = Float.parseFloat(transferAmountText.getText());

            if (con.transfer(accNo, persNo) == true) {
                con.transferMoney(transAm, accNo, personNumber);
            }

        } else if (transferChoiceCombo.getSelectedIndex() == 2) {
            float transAmoun = Float.parseFloat(transferAmountText.getText());
            int compNum = Integer.parseInt(textCompany.getText());
            String compName = companyNameText.getText();
            if (con.checkTransferCompany(compName, compNum) == true) {
                
                con.transferToCompany(transAmoun, compNum, personNumber);
                
            }
        }
    }//GEN-LAST:event_confirmButtonActionPerformed

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        String passs = con.md5(passwordField.getPassword());
        passwordAttempts++;
        if (con.checkPass(passs, passwordAttempts) == true && transferChoiceCombo.getSelectedIndex() != 0) {
            confirmButton.setVisible(true);
        } else if (transferChoiceCombo.getSelectedIndex() == 0) {
            JFrame framee = new JFrame();
            JOptionPane.showMessageDialog(framee, "Please choose type of transfer", "No choice made", 2);
        }
    }//GEN-LAST:event_okButtonActionPerformed

    private void transferChoiceComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transferChoiceComboActionPerformed
        if (transferChoiceCombo.getSelectedIndex() == 1) {
            personalLabel.setVisible(true);
            textPersonal.setVisible(true);
            transferToAccLabel.setVisible(true);
            transferToText.setVisible(true);
            labelCompany.setVisible(false);
            textCompany.setVisible(false);
            companyNameLabel.setVisible(false);
            companyNameText.setVisible(false);
        } else if (transferChoiceCombo.getSelectedIndex() == 2) {
            personalLabel.setVisible(false);
            transferToAccLabel.setVisible(false);
            transferToText.setVisible(false);
            textPersonal.setVisible(false);
            labelCompany.setVisible(true);
            textCompany.setVisible(true);
            companyNameLabel.setVisible(true);
            companyNameText.setVisible(true);
        }
    }//GEN-LAST:event_transferChoiceComboActionPerformed

    private void companyNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_companyNameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_companyNameTextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TransactionTransfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TransactionTransfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TransactionTransfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TransactionTransfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TransactionTransfer(email, personNumber).setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel companyNameLabel;
    private javax.swing.JTextField companyNameText;
    private javax.swing.JButton confirmButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel labelCompany;
    private javax.swing.JButton okButton;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel personalLabel;
    private javax.swing.JTextField textCompany;
    private javax.swing.JTextField textPersonal;
    private javax.swing.JTextField transferAmountText;
    private javax.swing.JComboBox transferChoiceCombo;
    private javax.swing.JTextField transferNote;
    private javax.swing.JLabel transferToAccLabel;
    private javax.swing.JTextField transferToText;
    // End of variables declaration//GEN-END:variables
}
